import {Order} from "@/types/order"

//genero ordini fittizi con AI
export const ORDERS_PAGE_1:Order[]=[
    {
    id: "1",
    dataOrdine: "11/03/2026",
    dataConsegnaPrevista: "18/03/2026",
    idOrdine: "ORD-00441",
    cliente: "Rossi Mario",
    statoOrdine: "Spedito",
    disponibilitaMagazzino: null,
    note: "",
    },
    {
        id: "2",
        dataOrdine: "12/03/2026",
        dataConsegnaPrevista: "21/03/2026",
        idOrdine: "ORD-00442",
        cliente: "Bianchi Sara",
        statoOrdine: "Da evadere",
        disponibilitaMagazzino: "Disponibile",
        note: "",
    },
    {
        id: "3",
        dataOrdine: "12/03/2026",
        dataConsegnaPrevista: "22/03/2026",
        idOrdine: "ORD-00443",
        cliente: "Verdi Luca",
        statoOrdine: "Da evadere",
        disponibilitaMagazzino: "Attesa fornitore",
        note: "",
    },
    {
        id: "4",
        dataOrdine: "13/03/2026",
        dataConsegnaPrevista: "20/03/2026",
        idOrdine: "ORD-00444",
        cliente: "Ferrari Anna",
        statoOrdine: "Da evadere",
        disponibilitaMagazzino: "Disponibile",
        note: "",
    },
    {
        id: "5",
        dataOrdine: "14/03/2026",
        dataConsegnaPrevista: "23/03/2026",
        idOrdine: "ORD-00445",
        cliente: "Conti Paolo",
        statoOrdine: "Spedito",
        disponibilitaMagazzino: null,
        note: "",
    },
    {
        id: "6",
        dataOrdine: "15/03/2026",
        dataConsegnaPrevista: "24/03/2026",
        idOrdine: "ORD-00446",
        cliente: "Russo Elena",
        statoOrdine: "Da evadere",
        disponibilitaMagazzino: "Attesa fornitore",
        note: "",
    },
    ];

    export const ORDERS_PAGE_2: Order[] = [
    {
        id: "7",
        dataOrdine: "15/03/2026",
        dataConsegnaPrevista: "24/03/2026",
        idOrdine: "ORD-00447",
        cliente: "Marino Giulia",
        statoOrdine: "Da evadere",
        disponibilitaMagazzino: "Disponibile",
        note: "",
    },
    {
        id: "8",
        dataOrdine: "16/03/2026",
        dataConsegnaPrevista: "25/03/2026",
        idOrdine: "ORD-00448",
        cliente: "Bruno Francesco",
        statoOrdine: "Spedito",
        disponibilitaMagazzino: null,
        note: "",
    },
    {
        id: "9",
        dataOrdine: "16/03/2026",
        dataConsegnaPrevista: "26/03/2026",
        idOrdine: "ORD-00449",
        cliente: "Gallo Marta",
        statoOrdine: "Da evadere",
        disponibilitaMagazzino: "Attesa fornitore",
        note: "",
    },
    {
        id: "10",
        dataOrdine: "17/03/2026",
        dataConsegnaPrevista: "27/03/2026",
        idOrdine: "ORD-00450",
        cliente: "Costa Davide",
        statoOrdine: "Da evadere",
        disponibilitaMagazzino: "Disponibile",
        note: "",
    },
    {
        id: "11",
        dataOrdine: "18/03/2026",
        dataConsegnaPrevista: "28/03/2026",
        idOrdine: "ORD-00451",
        cliente: "Ricci Valentina",
        statoOrdine: "Spedito",
        disponibilitaMagazzino: null,
        note: "",
    },
    {
        id: "12",
        dataOrdine: "19/03/2026",
        dataConsegnaPrevista: "29/03/2026",
        idOrdine: "ORD-00452",
        cliente: "Lombardi Pietro",
        statoOrdine: "Da evadere",
        disponibilitaMagazzino: "Disponibile",
        note: "",
    },
];

export const ALL_ORDERS = [...ORDERS_PAGE_1, ...ORDERS_PAGE_2];